hub-server: lobby
spawn:
  world: world
  x: 0.5
  y: 64.0
  z: 0.5
  yaw: 90.0
  pitch: 0.0
end-spawn:
  world: world_the_end
  x: 108.5
  y: 168.0
  z: 167.5
  yaw: -90.0
  pitch: 0.0
coins:
  kill-bonus: 10
  killstreak-bonus: 5
  kit-cost: 250